export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_STATUS = "CREATE_STATUS";
export const RETRIEVE_STATUSS = "RETRIEVE_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const DELETE_ALL_STATUSS = "DELETE_ALL_STATUS";